apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
  labels:
    app: mysql-deployment
spec:
  selector:
    app: mysql-deployment
  ports:
  - port: 3306
    targetPort: 3306
    name: mysql
