apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: default
spec:
  storageClassName: csi-hostpath-sc
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
