apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: wordpress-stack
type: Opaque
stringData:
  root-password: wordpress-2026
  user: wordpress
  password: wordpress-user-2026
